/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Insets;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import java.awt.image.BufferedImage;
import java.util.Locale;
import static java.util.Optional.empty;
import static javafx.scene.paint.Color.color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import rojerusan.RSPanelsSlider;

/**
 *
 * @author Nahomi
 */
public class Interfaz extends javax.swing.JFrame {
int ancho = 0;
int alto = 0;
int x=0,y=0;
public boolean maximizado = false;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    //Image ico = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/icono.png"));
    //this.setIconImage(ico);
        txtbnprod.setBackground(new Color(0,0,0,0));
        cmbbusquedas.setBackground(new Color(0,0,0,0));
        Border  empty;
        empty = BorderFactory.createEmptyBorder(1, 1, 1, 1);
        final Border compound, compound2, compound3 ;
        Color crl = (new Color(216, 236, 245));
        Color crl2 = (new Color(255, 255, 255));
        Color crl3 = (new Color(24, 160, 198));
        compound = BorderFactory.createCompoundBorder(empty, new redondear(crl));
        compound2 = BorderFactory.createCompoundBorder(empty, new redondear(crl2));
        compound3 = BorderFactory.createCompoundBorder(empty, new redondear(crl3));
        ptabla.setBorder(compound);
        pbuscar.setBorder(compound);
        pbuscart.setBorder(compound3);

//        prueba.setBorder(compound);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        pprincipal = new javax.swing.JPanel();
        pprodylot = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        rSPanelsSlider2 = new rojerusan.RSPanelsSlider();
        pvaciors2 = new javax.swing.JPanel();
        rSMaterialButtonRectangle24 = new rojerusan.RSMaterialButtonRectangle();
        ppresentacion = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        rSMaterialButtonRectangle25 = new rojerusan.RSMaterialButtonRectangle();
        jLabel20 = new javax.swing.JLabel();
        rSMaterialButtonRectangle27 = new rojerusan.RSMaterialButtonRectangle();
        jTextField7 = new javax.swing.JTextField();
        rSMaterialButtonRectangle28 = new rojerusan.RSMaterialButtonRectangle();
        jLabel7 = new javax.swing.JLabel();
        rSMaterialButtonRectangle29 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle30 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle26 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();
        psustancias = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        rSMaterialButtonRectangle31 = new rojerusan.RSMaterialButtonRectangle();
        jLabel22 = new javax.swing.JLabel();
        rSMaterialButtonRectangle33 = new rojerusan.RSMaterialButtonRectangle();
        jTextField8 = new javax.swing.JTextField();
        rSMaterialButtonRectangle34 = new rojerusan.RSMaterialButtonRectangle();
        jTextField9 = new javax.swing.JTextField();
        rSMaterialButtonRectangle35 = new rojerusan.RSMaterialButtonRectangle();
        jLabel23 = new javax.swing.JLabel();
        rSMaterialButtonRectangle36 = new rojerusan.RSMaterialButtonRectangle();
        jTextField10 = new javax.swing.JTextField();
        rSMaterialButtonRectangle37 = new rojerusan.RSMaterialButtonRectangle();
        jLabel24 = new javax.swing.JLabel();
        rSMaterialButtonRectangle38 = new rojerusan.RSMaterialButtonRectangle();
        jTextField11 = new javax.swing.JTextField();
        rSMaterialButtonRectangle39 = new rojerusan.RSMaterialButtonRectangle();
        jLabel25 = new javax.swing.JLabel();
        rSMaterialButtonRectangle40 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle32 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle41 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle42 = new rojerusan.RSMaterialButtonRectangle();
        pLote = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        rSMaterialButtonRectangle5 = new rojerusan.RSMaterialButtonRectangle();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        rSMaterialButtonRectangle6 = new rojerusan.RSMaterialButtonRectangle();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rSMaterialButtonRectangle11 = new rojerusan.RSMaterialButtonRectangle();
        jLabel13 = new javax.swing.JLabel();
        rSMaterialButtonRectangle12 = new rojerusan.RSMaterialButtonRectangle();
        rSDateChooser1 = new rojeru_san.componentes.RSDateChooser();
        jLabel14 = new javax.swing.JLabel();
        rSMaterialButtonRectangle13 = new rojerusan.RSMaterialButtonRectangle();
        jLabel15 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        rSMaterialButtonRectangle14 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle15 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle16 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle17 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle18 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle19 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle20 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle10 = new rojerusan.RSMaterialButtonRectangle();
        jPanel8 = new javax.swing.JPanel();
        rSPanelsSlider3 = new rojerusan.RSPanelsSlider();
        pproducto = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rSMaterialButtonRectangle3 = new rojerusan.RSMaterialButtonRectangle();
        jLabel6 = new javax.swing.JLabel();
        rSMaterialButtonRectangle4 = new rojerusan.RSMaterialButtonRectangle();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle8 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle9 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle21 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle22 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle23 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle7 = new rojerusan.RSMaterialButtonRectangle();
        pinfoprod = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        rSMaterialButtonRectangle44 = new rojerusan.RSMaterialButtonRectangle();
        jLabel27 = new javax.swing.JLabel();
        rSMaterialButtonRectangle45 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle47 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle46 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle43 = new rojerusan.RSMaterialButtonRectangle();
        pproductos = new javax.swing.JPanel();
        pbuscar = new javax.swing.JPanel();
        cmbbusquedas = new javax.swing.JComboBox<>();
        pbuscart = new javax.swing.JPanel();
        txtbnprod = new javax.swing.JTextField();
        ptabla = new javax.swing.JPanel();
        scrollgai1 = new javax.swing.JScrollPane();
        tableInventario = new rojerusan.RSTableMetro();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1245, 750));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(84, 159, 251));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_Cancel_30px_1.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_Enlarge_30px.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_Minus_30px.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 10)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("  Ingresar producto");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 35));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_Add_List_40px_1.png"))); // NOI18N
        jButton4.setToolTipText("");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_Add_List_55px.png"))); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 90, 71));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_Pill_40px.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_Pill_55px.png"))); // NOI18N
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 80, 72));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 10)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Productos");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 153, 81, 35));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.CardLayout());

        pprincipal.setBackground(new java.awt.Color(255, 255, 255));
        pprincipal.setName("pprincipal"); // NOI18N

        javax.swing.GroupLayout pprincipalLayout = new javax.swing.GroupLayout(pprincipal);
        pprincipal.setLayout(pprincipalLayout);
        pprincipalLayout.setHorizontalGroup(
            pprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        pprincipalLayout.setVerticalGroup(
            pprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );

        rSPanelsSlider1.add(pprincipal, "card4");

        pprodylot.setBackground(new java.awt.Color(255, 255, 255));
        pprodylot.setName("pprodylot"); // NOI18N
        pprodylot.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setLayout(new java.awt.CardLayout());

        pvaciors2.setBackground(new java.awt.Color(255, 255, 255));
        pvaciors2.setName("pvaciors2"); // NOI18N
        pvaciors2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSMaterialButtonRectangle24.setBackground(new java.awt.Color(33, 40, 105));
        pvaciors2.add(rSMaterialButtonRectangle24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 490, 600));

        rSPanelsSlider2.add(pvaciors2, "card3");

        ppresentacion.setBackground(new java.awt.Color(255, 255, 255));
        ppresentacion.setName("ppresentacion"); // NOI18N
        ppresentacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        jLabel19.setText(" PRESENTACIÓN:");
        ppresentacion.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 290, 70));

        rSMaterialButtonRectangle25.setBackground(new java.awt.Color(84, 159, 251));
        rSMaterialButtonRectangle25.setEnabled(false);
        ppresentacion.add(rSMaterialButtonRectangle25, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 486, 105));

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel20.setText("Nombre:");
        ppresentacion.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, 40));

        rSMaterialButtonRectangle27.setBackground(new java.awt.Color(255, 255, 255));
        ppresentacion.add(rSMaterialButtonRectangle27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 130, 60));

        jTextField7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 22)); // NOI18N
        ppresentacion.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 380, 40));

        rSMaterialButtonRectangle28.setBackground(new java.awt.Color(33, 40, 105));
        ppresentacion.add(rSMaterialButtonRectangle28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 420, 60));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel7.setText("Presentación:");
        ppresentacion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 150, -1));

        rSMaterialButtonRectangle29.setBackground(new java.awt.Color(255, 255, 255));
        ppresentacion.add(rSMaterialButtonRectangle29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 160, 60));

        rSMaterialButtonRectangle30.setBackground(new java.awt.Color(33, 40, 105));
        ppresentacion.add(rSMaterialButtonRectangle30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 420, 160));

        rSMaterialButtonRectangle26.setBackground(new java.awt.Color(231, 243, 249));
        ppresentacion.add(rSMaterialButtonRectangle26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 490, 560));

        rSMaterialButtonRectangle2.setText("Sustancias");
        rSMaterialButtonRectangle2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonRectangle2MouseClicked(evt);
            }
        });
        ppresentacion.add(rSMaterialButtonRectangle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 710, -1, -1));

        rSPanelsSlider2.add(ppresentacion, "card3");

        psustancias.setBackground(new java.awt.Color(255, 255, 255));
        psustancias.setName("psustancias"); // NOI18N
        psustancias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        jLabel21.setText("SUSTANCIAS:");
        psustancias.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 230, 70));

        rSMaterialButtonRectangle31.setBackground(new java.awt.Color(84, 159, 251));
        rSMaterialButtonRectangle31.setEnabled(false);
        psustancias.add(rSMaterialButtonRectangle31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 486, 105));

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel22.setText("sustancia 1:");
        psustancias.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, 40));

        rSMaterialButtonRectangle33.setBackground(new java.awt.Color(255, 255, 255));
        psustancias.add(rSMaterialButtonRectangle33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 160, 60));

        jTextField8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 22)); // NOI18N
        psustancias.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 380, 40));

        rSMaterialButtonRectangle34.setBackground(new java.awt.Color(33, 40, 105));
        psustancias.add(rSMaterialButtonRectangle34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 420, 60));

        jTextField9.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 22)); // NOI18N
        psustancias.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 380, 40));

        rSMaterialButtonRectangle35.setBackground(new java.awt.Color(33, 40, 105));
        psustancias.add(rSMaterialButtonRectangle35, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 420, 60));

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel23.setText("sustancia 2:");
        psustancias.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 40));

        rSMaterialButtonRectangle36.setBackground(new java.awt.Color(255, 255, 255));
        psustancias.add(rSMaterialButtonRectangle36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 160, 60));

        jTextField10.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 22)); // NOI18N
        psustancias.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 380, 40));

        rSMaterialButtonRectangle37.setBackground(new java.awt.Color(33, 40, 105));
        psustancias.add(rSMaterialButtonRectangle37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 420, 60));

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel24.setText("sustancia 3:");
        psustancias.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, 40));

        rSMaterialButtonRectangle38.setBackground(new java.awt.Color(255, 255, 255));
        psustancias.add(rSMaterialButtonRectangle38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 160, 60));

        jTextField11.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 22)); // NOI18N
        psustancias.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, 380, 40));

        rSMaterialButtonRectangle39.setBackground(new java.awt.Color(33, 40, 105));
        psustancias.add(rSMaterialButtonRectangle39, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 420, 60));

        jLabel25.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel25.setText("sustancia 1:");
        psustancias.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, -1, 40));

        rSMaterialButtonRectangle40.setBackground(new java.awt.Color(255, 255, 255));
        psustancias.add(rSMaterialButtonRectangle40, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 160, 60));

        rSMaterialButtonRectangle32.setBackground(new java.awt.Color(231, 243, 249));
        psustancias.add(rSMaterialButtonRectangle32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 490, 560));

        rSMaterialButtonRectangle41.setText("Más sustancias");
        psustancias.add(rSMaterialButtonRectangle41, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 710, 210, -1));

        rSMaterialButtonRectangle42.setText("Lote");
        rSMaterialButtonRectangle42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonRectangle42MouseClicked(evt);
            }
        });
        psustancias.add(rSMaterialButtonRectangle42, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 710, 210, -1));

        rSPanelsSlider2.add(psustancias, "card4");

        pLote.setBackground(new java.awt.Color(255, 255, 255));
        pLote.setName("pLote"); // NOI18N
        pLote.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        jLabel9.setText("LOTE:");
        pLote.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 100, 70));

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Q.");
        pLote.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 610, 40, 40));

        jTextField3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 22)); // NOI18N
        pLote.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 610, 210, 40));

        rSMaterialButtonRectangle5.setBackground(new java.awt.Color(84, 159, 251));
        rSMaterialButtonRectangle5.setEnabled(false);
        pLote.add(rSMaterialButtonRectangle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 486, 105));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Q.");
        pLote.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, 40, 40));

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Unidades");
        pLote.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, -1, 40));

        rSMaterialButtonRectangle6.setBackground(new java.awt.Color(33, 40, 105));
        pLote.add(rSMaterialButtonRectangle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 600, 310, 60));

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel16.setText("No. Lote:");
        pLote.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, 40));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel12.setText("Fecha de caducidad:");
        pLote.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 305, -1, 40));

        rSMaterialButtonRectangle11.setBackground(new java.awt.Color(255, 255, 255));
        pLote.add(rSMaterialButtonRectangle11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 295, 250, 60));

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel13.setText(" Cantidad:");
        pLote.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, 40));

        rSMaterialButtonRectangle12.setBackground(new java.awt.Color(255, 255, 255));
        pLote.add(rSMaterialButtonRectangle12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 150, 60));
        pLote.add(rSDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 366, 380, -1));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel14.setText("Costo:");
        pLote.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, -1, 40));

        rSMaterialButtonRectangle13.setBackground(new java.awt.Color(255, 255, 255));
        pLote.add(rSMaterialButtonRectangle13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 100, 60));

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel15.setText("Precio:");
        pLote.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, 80, 40));

        jTextField6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 22)); // NOI18N
        pLote.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 210, 40));

        jTextField4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 22)); // NOI18N
        pLote.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 380, 40));

        jTextField5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 22)); // NOI18N
        pLote.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 120, 40));

        rSMaterialButtonRectangle14.setBackground(new java.awt.Color(255, 255, 255));
        pLote.add(rSMaterialButtonRectangle14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 110, 60));

        rSMaterialButtonRectangle15.setBackground(new java.awt.Color(34, 84, 166));
        rSMaterialButtonRectangle15.setText("Ingresar Lote");
        rSMaterialButtonRectangle15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonRectangle15MouseClicked(evt);
            }
        });
        pLote.add(rSMaterialButtonRectangle15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 720, -1, -1));

        rSMaterialButtonRectangle16.setBackground(new java.awt.Color(255, 255, 255));
        pLote.add(rSMaterialButtonRectangle16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 130, 60));

        rSMaterialButtonRectangle17.setBackground(new java.awt.Color(33, 40, 105));
        pLote.add(rSMaterialButtonRectangle17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 420, 60));

        rSMaterialButtonRectangle18.setBackground(new java.awt.Color(33, 40, 105));
        pLote.add(rSMaterialButtonRectangle18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 355, 420, 60));

        rSMaterialButtonRectangle19.setBackground(new java.awt.Color(33, 40, 105));
        pLote.add(rSMaterialButtonRectangle19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 260, 60));

        rSMaterialButtonRectangle20.setBackground(new java.awt.Color(33, 40, 105));
        pLote.add(rSMaterialButtonRectangle20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 310, 60));

        rSMaterialButtonRectangle10.setBackground(new java.awt.Color(231, 243, 249));
        pLote.add(rSMaterialButtonRectangle10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 490, 560));

        rSPanelsSlider2.add(pLote, "card2");

        jPanel7.add(rSPanelsSlider2, "card2");

        pprodylot.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 510, 810));

        jPanel8.setLayout(new java.awt.CardLayout());

        pproducto.setBackground(new java.awt.Color(255, 255, 255));
        pproducto.setName("pproducto"); // NOI18N
        pproducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        jLabel10.setText("INGRESAR PRODUCTO:");
        pproducto.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 370, 70));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel8.setText("Nombre:");
        pproducto.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, 40));

        rSMaterialButtonRectangle3.setBackground(new java.awt.Color(255, 255, 255));
        pproducto.add(rSMaterialButtonRectangle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 130, 60));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel6.setText(" Descripción:");
        pproducto.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 150, -1));

        rSMaterialButtonRectangle4.setBackground(new java.awt.Color(255, 255, 255));
        pproducto.add(rSMaterialButtonRectangle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 160, 60));

        jTextField2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 22)); // NOI18N
        pproducto.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 380, 40));

        jTextField1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 22)); // NOI18N
        pproducto.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 250, 380, 40));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel5.setText("Lote actual:");
        pproducto.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, -1));

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(255, 255, 255));
        pproducto.add(rSMaterialButtonRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 160, 60));

        rSMaterialButtonRectangle8.setBackground(new java.awt.Color(84, 159, 251));
        rSMaterialButtonRectangle8.setEnabled(false);
        pproducto.add(rSMaterialButtonRectangle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 486, 105));

        rSMaterialButtonRectangle9.setBackground(new java.awt.Color(34, 84, 166));
        rSMaterialButtonRectangle9.setText("Presentacion");
        rSMaterialButtonRectangle9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonRectangle9MouseClicked(evt);
            }
        });
        pproducto.add(rSMaterialButtonRectangle9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 720, -1, -1));

        rSMaterialButtonRectangle21.setBackground(new java.awt.Color(33, 40, 105));
        pproducto.add(rSMaterialButtonRectangle21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 420, 130));

        rSMaterialButtonRectangle22.setBackground(new java.awt.Color(33, 40, 105));
        pproducto.add(rSMaterialButtonRectangle22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 420, 60));

        rSMaterialButtonRectangle23.setBackground(new java.awt.Color(33, 40, 105));
        pproducto.add(rSMaterialButtonRectangle23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 420, 60));

        rSMaterialButtonRectangle7.setBackground(new java.awt.Color(231, 243, 249));
        pproducto.add(rSMaterialButtonRectangle7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 490, 560));

        rSPanelsSlider3.add(pproducto, "card2");

        pinfoprod.setBackground(new java.awt.Color(255, 255, 255));
        pinfoprod.setName("pinfoprod"); // NOI18N
        pinfoprod.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel26.setText("Nombre del producto");
        pinfoprod.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 390, 40));

        jLabel28.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel28.setText("Nombre:");
        pinfoprod.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, 40));

        rSMaterialButtonRectangle44.setBackground(new java.awt.Color(255, 255, 255));
        pinfoprod.add(rSMaterialButtonRectangle44, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 130, 60));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel27.setText(" Descripción:");
        pinfoprod.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 150, -1));

        rSMaterialButtonRectangle45.setBackground(new java.awt.Color(183, 221, 237));
        pinfoprod.add(rSMaterialButtonRectangle45, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 430, 130));

        rSMaterialButtonRectangle47.setBackground(new java.awt.Color(183, 221, 237));
        pinfoprod.add(rSMaterialButtonRectangle47, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 430, 60));

        rSMaterialButtonRectangle46.setBackground(new java.awt.Color(255, 255, 255));
        pinfoprod.add(rSMaterialButtonRectangle46, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 160, 60));

        rSMaterialButtonRectangle43.setBackground(new java.awt.Color(33, 40, 105));
        pinfoprod.add(rSMaterialButtonRectangle43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 490, 600));

        rSPanelsSlider3.add(pinfoprod, "card3");

        jPanel8.add(rSPanelsSlider3, "card3");

        pprodylot.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 810));

        rSPanelsSlider1.add(pprodylot, "card2");

        pproductos.setBackground(new java.awt.Color(255, 255, 255));
        pproductos.setName("pproductos"); // NOI18N

        pbuscar.setBackground(new java.awt.Color(255, 255, 255));
        pbuscar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        pbuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbbusquedas.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 22)); // NOI18N
        cmbbusquedas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pbuscar.add(cmbbusquedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 230, 30));

        pbuscart.setBackground(new java.awt.Color(255, 255, 255));
        pbuscart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtbnprod.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 22)); // NOI18N
        txtbnprod.setForeground(new java.awt.Color(255, 255, 255));
        txtbnprod.setBorder(null);
        pbuscart.add(txtbnprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 580, 50));

        ptabla.setBackground(new java.awt.Color(255, 255, 255));

        tableInventario = new rojerusan.RSTableMetro(){
            public boolean isCellEditable(int rowIndex, int ColIndex){
                return false;
            }
        };
        tableInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", " Nombre", "Descripción", "Cantidad", "Precio unitario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableInventario.setColorBackgoundHead(new java.awt.Color(22, 54, 77));
        tableInventario.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tableInventario.setColorBordeHead(new java.awt.Color(255, 255, 255));
        tableInventario.setColorFilasBackgound1(new java.awt.Color(163, 214, 249));
        tableInventario.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tableInventario.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tableInventario.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tableInventario.setColorSelBackgound(new java.awt.Color(22, 54, 77));
        tableInventario.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        tableInventario.setFuenteFilas(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        tableInventario.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        tableInventario.setFuenteHead(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        tableInventario.setGrosorBordeFilas(0);
        tableInventario.setGrosorBordeHead(0);
        tableInventario.setRowHeight(22);
        tableInventario.getTableHeader().setReorderingAllowed(false);
        scrollgai1.setViewportView(tableInventario);

        javax.swing.GroupLayout ptablaLayout = new javax.swing.GroupLayout(ptabla);
        ptabla.setLayout(ptablaLayout);
        ptablaLayout.setHorizontalGroup(
            ptablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ptablaLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(scrollgai1)
                .addGap(0, 0, 0))
        );
        ptablaLayout.setVerticalGroup(
            ptablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ptablaLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(scrollgai1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        jLabel1.setText("Productos");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        jLabel3.setText("PRODUCTOS:");

        javax.swing.GroupLayout pproductosLayout = new javax.swing.GroupLayout(pproductos);
        pproductos.setLayout(pproductosLayout);
        pproductosLayout.setHorizontalGroup(
            pproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pproductosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pproductosLayout.createSequentialGroup()
                        .addComponent(ptabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(pproductosLayout.createSequentialGroup()
                        .addGroup(pproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pproductosLayout.createSequentialGroup()
                                .addComponent(pbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pbuscart, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(163, Short.MAX_VALUE))))
            .addGroup(pproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pproductosLayout.createSequentialGroup()
                    .addGap(0, 441, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 442, Short.MAX_VALUE)))
        );
        pproductosLayout.setVerticalGroup(
            pproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pproductosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pbuscart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ptabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45))
            .addGroup(pproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pproductosLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        rSPanelsSlider1.add(pproductos, "card3");

        jPanel6.add(rSPanelsSlider1, "card2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        if(maximizado == false) 
        {
            Interfaz.this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            maximizado = true;
        }
        else
        {
            Interfaz.this.setExtendedState(JFrame.NORMAL);
            maximizado = false;
        } 
    }//GEN-LAST:event_jButton2MouseClicked

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        x = evt.getX();
        y =evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x,this.getLocation().y + evt.getY() -  y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        x = evt.getX();
        y =evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x,this.getLocation().y + evt.getY() -  y);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        rSPanelsSlider1.setPanelSlider(pproductos, RSPanelsSlider.DIRECT.LEFT);
        jButton2.setEnabled(true);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        rSPanelsSlider1.setPanelSlider(pprodylot, RSPanelsSlider.DIRECT.RIGHT);
        rSPanelsSlider3.setPanelSlider( (int) 1.2,pproducto, RSPanelsSlider.DIRECT.LEFT);
        rSPanelsSlider2.setPanelSlider( (int) 1.2,pvaciors2, RSPanelsSlider.DIRECT.LEFT);
        jButton2.setEnabled(false);
    }//GEN-LAST:event_jButton4MouseClicked

    private void rSMaterialButtonRectangle9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle9MouseClicked
        //ingresar producto
        rSPanelsSlider3.setPanelSlider((int) 1.2, pinfoprod, RSPanelsSlider.DIRECT.RIGHT);
        rSPanelsSlider2.setPanelSlider((int) 1.2, ppresentacion, RSPanelsSlider.DIRECT.LEFT);
    }//GEN-LAST:event_rSMaterialButtonRectangle9MouseClicked

    private void rSMaterialButtonRectangle2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle2MouseClicked
        rSPanelsSlider3.setPanelSlider((int) 1.2, pinfoprod, RSPanelsSlider.DIRECT.RIGHT);
        rSPanelsSlider2.setPanelSlider((int) 1.2, psustancias, RSPanelsSlider.DIRECT.LEFT);
    }//GEN-LAST:event_rSMaterialButtonRectangle2MouseClicked

    private void rSMaterialButtonRectangle42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle42MouseClicked
        rSPanelsSlider3.setPanelSlider((int) 1.2, pinfoprod, RSPanelsSlider.DIRECT.RIGHT);
        rSPanelsSlider2.setPanelSlider((int) 1.2, pLote, RSPanelsSlider.DIRECT.LEFT);
       
    }//GEN-LAST:event_rSMaterialButtonRectangle42MouseClicked

    private void rSMaterialButtonRectangle15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle15MouseClicked
        rSPanelsSlider1.setPanelSlider( (int) 1.2,pprincipal, RSPanelsSlider.DIRECT.LEFT);
        rSPanelsSlider3.setPanelSlider( (int) 1.2,pproducto, RSPanelsSlider.DIRECT.LEFT);
        rSPanelsSlider2.setPanelSlider( (int) 1.2,pvaciors2, RSPanelsSlider.DIRECT.LEFT);
    }//GEN-LAST:event_rSMaterialButtonRectangle15MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbbusquedas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel pLote;
    private javax.swing.JPanel pbuscar;
    private javax.swing.JPanel pbuscart;
    private javax.swing.JPanel pinfoprod;
    private javax.swing.JPanel ppresentacion;
    private javax.swing.JPanel pprincipal;
    private javax.swing.JPanel pproducto;
    private javax.swing.JPanel pproductos;
    private javax.swing.JPanel pprodylot;
    private javax.swing.JPanel psustancias;
    private javax.swing.JPanel ptabla;
    private javax.swing.JPanel pvaciors2;
    private rojeru_san.componentes.RSDateChooser rSDateChooser1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle10;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle11;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle12;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle13;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle14;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle15;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle16;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle17;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle18;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle19;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle20;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle21;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle22;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle23;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle24;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle25;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle26;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle27;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle28;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle29;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle3;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle30;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle31;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle32;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle33;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle34;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle35;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle36;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle37;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle38;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle39;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle4;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle40;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle41;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle42;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle43;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle44;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle45;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle46;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle47;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle5;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle6;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle7;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle8;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle9;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    private rojerusan.RSPanelsSlider rSPanelsSlider2;
    private rojerusan.RSPanelsSlider rSPanelsSlider3;
    private javax.swing.JScrollPane scrollgai1;
    private rojerusan.RSTableMetro tableInventario;
    private javax.swing.JTextField txtbnprod;
    // End of variables declaration//GEN-END:variables
}
