/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.sun.awt.AWTUtilities;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Paint;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D;
import rojerusan.RSPanelsSlider;

/**
 *
 * @author Nahomi
 */
public class login extends javax.swing.JFrame {
    private Color colorPrimario = new Color(0x666f7f);
    private Color colorSecundario = new Color(0x262d3d);
    private Color colorContorno = new Color(0x262d3d);
    private int arcw=20;
    private int arch=20;
    public boolean click = false;
    public boolean click2 = false;
    /**
     * Creates new form login
     */
    public login() 
        {
        initComponents();
        this.setLocationRelativeTo(null);
        AWTUtilities.setWindowOpaque(this, false);
        cmbusuario.setBackground(new Color(0,0,0,0));
        }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        rSPanelsSlider2 = new rojerusan.RSPanelsSlider();
        jPanel3 = new javax.swing.JPanel();
        btnminimizar = new javax.swing.JButton();
        btncerrar = new javax.swing.JButton();
        cmbusuario = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        usercontrasenia = new javax.swing.JPasswordField();
        btnolvcon = new rojerusan.RSMaterialButtonRectangle();
        btningresar = new rojerusan.RSMaterialButtonRectangle();
        btnpanelreg = new rojerusan.RSMaterialButtonRectangle();
        jLabel3 = new javax.swing.JLabel();
        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        vacio = new javax.swing.JPanel();
        registrar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        contrasenia = new javax.swing.JPasswordField();
        btnregistrar = new javax.swing.JLabel();
        Registrar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rSPanelsSlider3 = new rojerusan.RSPanelsSlider();
        pvacio = new javax.swing.JPanel();
        prcontrasenia = new javax.swing.JPanel();
        ncontrasenia = new javax.swing.JPasswordField();
        btnguardarnc = new rojerusan.RSMaterialButtonRectangle();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.CardLayout());

        rSPanelsSlider2.setOpaque(false);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_Chevron_Down_35px.png"))); // NOI18N
        btnminimizar.setBorder(null);
        btnminimizar.setBorderPainted(false);
        btnminimizar.setContentAreaFilled(false);
        btnminimizar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_Chevron_Down_55px.png"))); // NOI18N
        btnminimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnminimizarMouseClicked(evt);
            }
        });
        jPanel3.add(btnminimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 60, 57));

        btncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_Cancel_35px_1.png"))); // NOI18N
        btncerrar.setBorder(null);
        btncerrar.setBorderPainted(false);
        btncerrar.setContentAreaFilled(false);
        btncerrar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_Cancel_55px_1.png"))); // NOI18N
        btncerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncerrarMouseClicked(evt);
            }
        });
        jPanel3.add(btncerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 60, 57));

        cmbusuario.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        cmbusuario.setForeground(new java.awt.Color(58, 120, 173));
        cmbusuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbusuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 236, 242)));
        jPanel3.add(cmbusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 290, 40));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel9.setText("Usuario:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 70, -1));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel10.setText("Contraseña:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 397, 110, -1));

        usercontrasenia.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        usercontrasenia.setForeground(new java.awt.Color(58, 120, 173));
        usercontrasenia.setText("jPasswordField1");
        usercontrasenia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 236, 242)));
        usercontrasenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usercontraseniaMouseClicked(evt);
            }
        });
        jPanel3.add(usercontrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 428, 290, 40));

        btnolvcon.setBackground(new java.awt.Color(10, 46, 123));
        btnolvcon.setText("¿Olvidaste tu contraseña?");
        btnolvcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnolvcon.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        btnolvcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnolvconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnolvconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnolvconMouseExited(evt);
            }
        });
        jPanel3.add(btnolvcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 546, 250, 60));

        btningresar.setBackground(new java.awt.Color(10, 46, 123));
        btningresar.setText("Ingresar");
        btningresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btningresar.setFont(new java.awt.Font("Segoe UI Historic", 0, 17)); // NOI18N
        btningresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btningresarMouseClicked(evt);
            }
        });
        jPanel3.add(btningresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 250, 60));

        btnpanelreg.setBackground(new java.awt.Color(39, 175, 213));
        btnpanelreg.setText("¿No tienes cuenta?");
        btnpanelreg.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        btnpanelreg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpanelregMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpanelregMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpanelregMouseExited(evt);
            }
        });
        jPanel3.add(btnpanelreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 170, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login2.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 450, 680));

        rSPanelsSlider2.add(jPanel3, "card3");

        jPanel2.add(rSPanelsSlider2, "card3");

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 455, -1));

        rSPanelsSlider1.setOpaque(false);

        vacio.setName("vacio"); // NOI18N
        vacio.setOpaque(false);

        javax.swing.GroupLayout vacioLayout = new javax.swing.GroupLayout(vacio);
        vacio.setLayout(vacioLayout);
        vacioLayout.setHorizontalGroup(
            vacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        vacioLayout.setVerticalGroup(
            vacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        rSPanelsSlider1.add(vacio, "card4");

        registrar.setName("registrar"); // NOI18N
        registrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel8.setText("Contraseña:");
        registrar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 110, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel5.setText("Usuario:");
        registrar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 70, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel7.setText("Apellido:");
        registrar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 70, -1));

        txtusuario.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txtusuario.setForeground(new java.awt.Color(58, 120, 173));
        txtusuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 236, 255)));
        registrar.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 280, 40));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel6.setText("Nombre:");
        registrar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 70, -1));

        txtnombre.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(58, 120, 173));
        txtnombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 236, 255)));
        registrar.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 280, 40));

        txtapellido.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txtapellido.setForeground(new java.awt.Color(58, 120, 173));
        txtapellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 236, 255)));
        registrar.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 280, 40));

        contrasenia.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        contrasenia.setForeground(new java.awt.Color(58, 120, 173));
        contrasenia.setText("jPasswordField1");
        contrasenia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 236, 242)));
        contrasenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contraseniaMouseClicked(evt);
            }
        });
        registrar.add(contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 280, 40));

        btnregistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnregistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnregistrarMouseClicked(evt);
            }
        });
        registrar.add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 240, 40));

        Registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registro.png"))); // NOI18N
        registrar.add(Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 450, 680));

        rSPanelsSlider1.add(registrar, "card3");

        getContentPane().add(rSPanelsSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 7, 450, 650));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.CardLayout());

        rSPanelsSlider3.setOpaque(false);

        pvacio.setName("pvacio"); // NOI18N
        pvacio.setOpaque(false);

        javax.swing.GroupLayout pvacioLayout = new javax.swing.GroupLayout(pvacio);
        pvacio.setLayout(pvacioLayout);
        pvacioLayout.setHorizontalGroup(
            pvacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pvacioLayout.setVerticalGroup(
            pvacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        rSPanelsSlider3.add(pvacio, "card3");

        prcontrasenia.setBackground(new java.awt.Color(249, 247, 247));
        prcontrasenia.setName("prcontrasenia"); // NOI18N
        prcontrasenia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ncontrasenia.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        ncontrasenia.setForeground(new java.awt.Color(58, 120, 173));
        ncontrasenia.setText("jPasswordField1");
        ncontrasenia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 236, 242)));
        ncontrasenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ncontraseniaMouseClicked(evt);
            }
        });
        prcontrasenia.add(ncontrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 273, 40));

        btnguardarnc.setBackground(new java.awt.Color(10, 46, 123));
        btnguardarnc.setText("Guardar");
        btnguardarnc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnguardarnc.setFont(new java.awt.Font("Segoe UI Historic", 0, 17)); // NOI18N
        btnguardarnc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnguardarncMouseClicked(evt);
            }
        });
        prcontrasenia.add(btnguardarnc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 250, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_Forgot_Password_40px.png"))); // NOI18N
        prcontrasenia.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 50, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Recuperar Contraseña");
        prcontrasenia.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 30, 280, 50));

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonRectangle1.setText("rSMaterialButtonRectangle1");
        prcontrasenia.add(rSMaterialButtonRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 140, 330, 190));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        prcontrasenia.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -5, -1, 250));

        rSPanelsSlider3.add(prcontrasenia, "card2");

        jPanel1.add(rSPanelsSlider3, "card2");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 400, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpanelregMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpanelregMouseEntered
        rSPanelsSlider1.setPanelSlider((int)1.2, registrar, RSPanelsSlider.DIRECT.RIGHT);
        click = false;
    }//GEN-LAST:event_btnpanelregMouseEntered

    private void btnpanelregMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpanelregMouseExited
        if(click == false)
        {
                   rSPanelsSlider1.setPanelSlider( vacio, RSPanelsSlider.DIRECT.LEFT);
         }
   else    rSPanelsSlider1.setPanelSlider( registrar, RSPanelsSlider.DIRECT.RIGHT); 
    }//GEN-LAST:event_btnpanelregMouseExited
  
    private void btnpanelregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpanelregMouseClicked
        click = true;
        rSPanelsSlider1.setPanelSlider((int)1.2, registrar, RSPanelsSlider.DIRECT.RIGHT);
    }//GEN-LAST:event_btnpanelregMouseClicked

    private void btnregistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistrarMouseClicked
        rSPanelsSlider1.setPanelSlider( vacio, RSPanelsSlider.DIRECT.LEFT);
        //proceso registrar
        
    }//GEN-LAST:event_btnregistrarMouseClicked

    private void contraseniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraseniaMouseClicked
       contrasenia.setText("");
    }//GEN-LAST:event_contraseniaMouseClicked

    private void ncontraseniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ncontraseniaMouseClicked
        ncontrasenia.setText("");
    }//GEN-LAST:event_ncontraseniaMouseClicked

    private void usercontraseniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usercontraseniaMouseClicked
        usercontrasenia.setText("");
    }//GEN-LAST:event_usercontraseniaMouseClicked

    private void btnolvconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnolvconMouseEntered
        rSPanelsSlider3.setPanelSlider((int)1.2,prcontrasenia, RSPanelsSlider.DIRECT.LEFT);
        click2 = false;
    }//GEN-LAST:event_btnolvconMouseEntered

    private void btnolvconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnolvconMouseExited
        if(click2 == false)
        {
                   rSPanelsSlider3.setPanelSlider( pvacio, RSPanelsSlider.DIRECT.RIGHT);
         }
        else    rSPanelsSlider3.setPanelSlider( prcontrasenia, RSPanelsSlider.DIRECT.LEFT); 
    }//GEN-LAST:event_btnolvconMouseExited

    private void btnolvconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnolvconMouseClicked
        click2 = true;
        rSPanelsSlider3.setPanelSlider((int)1.2,prcontrasenia, RSPanelsSlider.DIRECT.LEFT);
    }//GEN-LAST:event_btnolvconMouseClicked

    private void btnguardarncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarncMouseClicked
        rSPanelsSlider3.setPanelSlider( pvacio, RSPanelsSlider.DIRECT.RIGHT);
        //proceso guardar nueva contrasenia
    }//GEN-LAST:event_btnguardarncMouseClicked

    private void btnminimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnminimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnminimizarMouseClicked

    private void btncerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrarMouseClicked
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btncerrarMouseClicked

    private void btningresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btningresarMouseClicked
        //Ingresar usuario
        this.dispose();
        splash s = new splash();
        s.setVisible(true);
    }//GEN-LAST:event_btningresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Registrar;
    private javax.swing.JButton btncerrar;
    private rojerusan.RSMaterialButtonRectangle btnguardarnc;
    private rojerusan.RSMaterialButtonRectangle btningresar;
    private javax.swing.JButton btnminimizar;
    private rojerusan.RSMaterialButtonRectangle btnolvcon;
    private rojerusan.RSMaterialButtonRectangle btnpanelreg;
    private javax.swing.JLabel btnregistrar;
    private javax.swing.JComboBox<String> cmbusuario;
    private javax.swing.JPasswordField contrasenia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField ncontrasenia;
    private javax.swing.JPanel prcontrasenia;
    private javax.swing.JPanel pvacio;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    private rojerusan.RSPanelsSlider rSPanelsSlider2;
    private rojerusan.RSPanelsSlider rSPanelsSlider3;
    private javax.swing.JPanel registrar;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtusuario;
    private javax.swing.JPasswordField usercontrasenia;
    private javax.swing.JPanel vacio;
    // End of variables declaration//GEN-END:variables
}
